name: Blauhaus Packages
on:
  push:
    branches:
    - release/*

jobs:

  build:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v1
     - name: Set Version
       run: |
        npm install @actions/core --save
        node ./scripts/getversion.js
     - name: Build NuGet Packages
       run: |
        dotnet build ./src/Blauhaus.HttpClientService.sln --configuration Release
        dotnet test ./src/Blauhaus.HttpClientService.sln
        dotnet pack ./src/Blauhaus.HttpClientService/Blauhaus.HttpClientService.csproj -p:PackageVersion=${VERSION_NAME} --no-build --output ./ --configuration Release 
        dotnet pack ./src/Blauhaus.HttpClientService.Abstractions/Blauhaus.HttpClientService.Abstractions.csproj -p:PackageVersion=${VERSION_NAME} --no-build --output ./ --configuration Release 
        dotnet pack ./src/Blauhaus.HttpClientService.TestHelpers/Blauhaus.HttpClientService.TestHelpers.csproj -p:PackageVersion=${VERSION_NAME} --no-build --output ./ --configuration Release 
     - name: Deploy NuGet Packages
       run: |
        dotnet nuget push /home/runner/work/Blauhaus.HttpClientService/Blauhaus.HttpClientService/Blauhaus.HttpClientService.${VERSION_NAME}.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
        dotnet nuget push /home/runner/work/Blauhaus.HttpClientService/Blauhaus.HttpClientService/Blauhaus.HttpClientService.Abstractions.${VERSION_NAME}.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
        dotnet nuget push /home/runner/work/Blauhaus.HttpClientService/Blauhaus.HttpClientService/Blauhaus.HttpClientService.TestHelpers.${VERSION_NAME}.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json